project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "Bienvenidos a mi blog"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Lesly Sierra."
    right:
      - icon: github
        href: https://github.com/LeslyMSF/
      - icon: linkedin
        href: https://www.linkedin.com/in/lesly-sierra-fontalvo/
      - icon: envelope
        href: mailto:leslyf@uninorte.edu.com

  navbar:
    right:
      - icon: newspaper
        href: https://scholar.google.com/citations?user=QMgnwJsAAAAJ&hl=es&oi=ao
      - icon: github
        href: https://github.com/LeslyMSF/
      - icon: linkedin
        href: https://www.linkedin.com/in/lesly-sierra-fontalvo/

lang: "es"

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

execute:
  freeze: true
